# Generated by Django 3.1.6 on 2021-09-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tubeuser',
            name='subscribed_users',
            field=models.ManyToManyField(blank=True, related_name='_tubeuser_subscribed_users_+', to='community.TubeUser'),
        ),
        migrations.AlterField(
            model_name='tubeuser',
            name='viewed_users',
            field=models.ManyToManyField(blank=True, related_name='_tubeuser_viewed_users_+', to='community.TubeUser'),
        ),
    ]
