# Generated by Django 3.1.6 on 2021-09-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tubeuser',
            name='tube_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='embed_script',
            field=models.TextField(blank=True, null=True),
        ),
    ]
