# Generated by Django 3.1.6 on 2021-09-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20210914_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tubeuser',
            name='subscribed_users',
            field=models.ManyToManyField(blank=True, related_name='subscribe_by_the_user', to='community.TubeUser'),
        ),
        migrations.AlterField(
            model_name='tubeuser',
            name='viewed_users',
            field=models.ManyToManyField(blank=True, related_name='viewed_the_user', to='community.TubeUser'),
        ),
    ]
